# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github_token:
    description: 'Token used for publish gh-pages'
    required: true
    default: 'fonts'
  fonts_dir:
    description: 'directory where original fonts are stored'
    required: false
    default: 'fonts'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.fonts_dir }}
